namespace Incursa.Generators.AppDefinitions.Emission;

using Incursa.Generators.AppDefinitions.Config;
using Incursa.Generators.AppDefinitions.Model;
using Incursa.Generators.AppDefinitions.Validation;

internal static class EmitterUtilities
{
    public const string ToolName = "Incursa.Generators.Tool";
    public const string ToolCommandName = "incursa-appdefs";
    public const string GeneratedMarker = "Generated by Incursa.Generators.Tool";
    public const string DefaultNamespaceMode = "default";
    public const string FeatureNamespaceMode = "feature";

    public static string BuildNamespace(ResolvedOutputTarget target, string relativeDirectory)
    {
        if (string.Equals(target.NamespaceMode, FeatureNamespaceMode, StringComparison.Ordinal))
        {
            return BuildFeatureNamespace(target, relativeDirectory, featureName: null);
        }

        if (!target.AppendRelativePathToNamespace || string.IsNullOrWhiteSpace(relativeDirectory))
        {
            return target.Namespace;
        }

        var suffix = string.Join(
            ".",
            relativeDirectory
                .Split(['/', '\\'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                .Select(CSharpNaming.SanitizeNamespaceSegment));

        return string.IsNullOrWhiteSpace(suffix)
            ? target.Namespace
            : $"{target.Namespace}.{suffix}";
    }

    public static string BuildFeatureNamespace(ResolvedOutputTarget target, PageFeatureDefinition feature)
    {
        return BuildFeatureNamespace(target, feature.RelativeDirectory, feature.Name);
    }

    public static string BuildFeatureNamespace(ResolvedOutputTarget target, string relativeDirectory, string? featureName)
    {
        var segments = new List<string> { target.Namespace };

        if (target.AppendRelativePathToNamespace && !string.IsNullOrWhiteSpace(relativeDirectory))
        {
            segments.AddRange(relativeDirectory
                .Split(['/', '\\'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                .Select(CSharpNaming.SanitizeNamespaceSegment));
        }

        if (string.Equals(target.NamespaceMode, FeatureNamespaceMode, StringComparison.Ordinal) && !string.IsNullOrWhiteSpace(featureName))
        {
            segments.Add(CSharpNaming.SanitizeNamespaceSegment(featureName));
        }

        return string.Join(".", segments.Where(static segment => !string.IsNullOrWhiteSpace(segment)));
    }

    public static string BuildRelativePath(ResolvedOutputTarget target, string relativeDirectory, string fileName)
    {
        if (!target.PreserveDefinitionFolders || string.IsNullOrWhiteSpace(relativeDirectory))
        {
            return fileName;
        }

        return $"{NormalizeRelativePath(relativeDirectory)}/{fileName}";
    }

    public static string BuildAbsolutePath(ResolvedOutputTarget target, string relativePath)
    {
        return Path.GetFullPath(Path.Combine(target.Directory, relativePath.Replace('/', Path.DirectorySeparatorChar)));
    }

    public static void AppendHeader(CodeBuilder builder, string targetName, string targetKind, string relativePath)
    {
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine($"// {GeneratedMarker}");
        builder.AppendLine($"// Command: {ToolCommandName}");
        builder.AppendLine("// Do not edit this file by hand. Your changes will be overwritten.");
        builder.AppendLine($"// Ownership: target={targetName}; kind={targetKind}; relative-path={NormalizeRelativePath(relativePath)}");
        builder.AppendLine();
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
    }

    public static bool IsOwnedGeneratedFile(string content, string targetName, string targetKind, string relativePath)
    {
        var normalizedRelativePath = NormalizeRelativePath(relativePath);

        return content.Contains($"// {GeneratedMarker}", StringComparison.Ordinal)
            && content.Contains($"// Ownership: target={targetName}; kind={targetKind}; relative-path={normalizedRelativePath}", StringComparison.Ordinal);
    }

    public static string ResolveImportNamespace(ResolvedOutputTarget target, string importName)
    {
        if (target.Imports.TryGetValue(importName, out var importNamespace) && !string.IsNullOrWhiteSpace(importNamespace))
        {
            return importNamespace;
        }

        return target.Namespace;
    }

    public static string GetOperationMethodName(OperationDefinition operation)
    {
        return operation.Name.EndsWith("Async", StringComparison.Ordinal) ? operation.Name : $"{operation.Name}Async";
    }

    public static string? GetOperationResultType(PageFeatureDefinition feature, OperationDefinition operation)
    {
        if (!string.IsNullOrWhiteSpace(operation.ReturnType))
        {
            return operation.ReturnType;
        }

        if (operation.Returns is not null)
        {
            return operation.Returns.Type;
        }

        return string.Equals(operation.Name, "InitVm", StringComparison.Ordinal)
            ? feature.ViewModelTypeName
            : null;
    }

    public static string FormatAsyncReturnType(string? rawType)
    {
        if (string.IsNullOrWhiteSpace(rawType))
        {
            return "Task";
        }

        return IsTaskLikeReturnType(rawType)
            ? NormalizeTaskLikeReturnType(rawType)
            : $"Task<{rawType}>";
    }

    public static IReadOnlyList<MethodParameter> BuildInterfaceMethodParameters(PageFeatureDefinition feature, OperationDefinition operation)
    {
        var parameters = new List<MethodParameter>();
        parameters.AddRange(feature.PageParameters.Select(static parameter => CreateMethodParameter(parameter.Type, parameter.Name, parameter.Required)));
        parameters.AddRange(operation.Parameters.Select(static parameter => CreateMethodParameter(parameter.Type, parameter.Name, parameter.Required)));
        parameters.AddRange(operation.RouteParameters.Select(static parameter => CreateMethodParameter(parameter.Type, parameter.Name, parameter.Required)));
        parameters.AddRange(operation.QueryParameters.Select(static parameter => CreateMethodParameter(parameter.Type, parameter.Name, parameter.Required)));

        if (operation.BodyParameter is not null)
        {
            parameters.Add(new MethodParameter(FormatTypeName(operation.BodyParameter.Type), "body"));
        }

        return parameters;
    }

    public static IReadOnlyList<MethodParameter> BuildAdapterMethodParameters(OperationDefinition operation)
    {
        var parameters = new List<MethodParameter>();
        parameters.AddRange(operation.Parameters.Select(static parameter => CreateMethodParameter(parameter.Type, parameter.Name, parameter.Required)));
        parameters.AddRange(operation.RouteParameters.Select(static parameter => CreateMethodParameter(parameter.Type, parameter.Name, parameter.Required)));
        parameters.AddRange(operation.QueryParameters.Select(static parameter => CreateMethodParameter(parameter.Type, parameter.Name, parameter.Required)));

        if (operation.BodyParameter is not null)
        {
            parameters.Add(new MethodParameter(FormatTypeName(operation.BodyParameter.Type), "body"));
        }

        return parameters;
    }

    public static string FormatMethodSignature(IReadOnlyList<MethodParameter> parameters, bool includeCancellationToken)
    {
        var parts = parameters.Select(static parameter => $"{parameter.Type} {parameter.Name}").ToList();
        if (includeCancellationToken)
        {
            parts.Add("CancellationToken cancellationToken");
        }

        return string.Join(", ", parts);
    }

    public static MethodParameter CreateMethodParameter(string rawType, string name, bool required)
    {
        return new MethodParameter(FormatTypeName(rawType, nullable: !required), name);
    }

    public static string FormatAdapterInvocationArguments(PageFeatureDefinition feature, OperationDefinition operation)
    {
        var arguments = new List<string>();
        arguments.AddRange(feature.PageParameters.Select(static parameter => ToPascalCase(parameter.Name)));
        arguments.AddRange(operation.Parameters.Select(static parameter => parameter.Name));
        arguments.AddRange(operation.RouteParameters.Select(static parameter => parameter.Name));
        arguments.AddRange(operation.QueryParameters.Select(static parameter => parameter.Name));

        if (operation.BodyParameter is not null)
        {
            arguments.Add("body");
        }

        arguments.Add("cancellationToken");
        return string.Join(", ", arguments);
    }

    public static string FormatTypeName(string rawType, bool nullable = false)
    {
        if (!nullable || rawType.EndsWith("?", StringComparison.Ordinal))
        {
            return rawType;
        }

        return $"{rawType}?";
    }

    public static bool IsTaskLikeReturnType(string typeName)
    {
        var rootTypeName = GetTopLevelTypeName(typeName);
        var simpleTypeName = GetSimpleTypeName(rootTypeName);
        return string.Equals(simpleTypeName, "Task", StringComparison.Ordinal)
            || string.Equals(simpleTypeName, "ValueTask", StringComparison.Ordinal);
    }

    public static string NormalizeTaskLikeReturnType(string typeName)
    {
        return typeName switch
        {
            "System.Threading.Tasks.Task" => "Task",
            "System.Threading.Tasks.ValueTask" => "ValueTask",
            _ => typeName
                .Replace("System.Threading.Tasks.Task<", "Task<", StringComparison.Ordinal)
                .Replace("System.Threading.Tasks.ValueTask<", "ValueTask<", StringComparison.Ordinal),
        };
    }

    public static string BuildPropertyDeclaration(PropertyDefinition property, bool useInitAccessor)
    {
        var typeName = FormatTypeName(property.Type, property.Nullable);
        var accessor = useInitAccessor || !property.Settable ? "init;" : "set;";
        var requiredModifier = property.Required && !typeName.EndsWith("?", StringComparison.Ordinal) ? "required " : string.Empty;
        var defaultInitializer = !requiredModifier.Equals("required ", StringComparison.Ordinal) && NeedsDefaultInitializer(typeName)
            ? " = default!;"
            : string.Empty;

        return $"public {requiredModifier}{typeName} {property.Name} {{ get; {accessor} }}{defaultInitializer}";
    }

    public static string ToPascalCase(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return value;
        }

        if (value.IndexOfAny(['-', '_', ' ']) >= 0)
        {
            var parts = value
                .Split(['-', '_', ' '], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                .Select(static part => char.ToUpperInvariant(part[0]) + part[1..]);

            return string.Concat(parts);
        }

        return char.ToUpperInvariant(value[0]) + value[1..];
    }

    private static bool NeedsDefaultInitializer(string typeName)
    {
        if (typeName.EndsWith("?", StringComparison.Ordinal))
        {
            return false;
        }

        var normalized = typeName.Split(['<', '[', '(', ','], StringSplitOptions.TrimEntries)[0];
        return !TypeNameClassifier.IsValueType(normalized);
    }

    public static string NormalizeRelativePath(string path)
    {
        return path.Replace('\\', '/');
    }

    private static string GetTopLevelTypeName(string rawType)
    {
        return rawType
            .Split(['<', '[', '(', ','], StringSplitOptions.TrimEntries)[0]
            .Replace("global::", string.Empty, StringComparison.Ordinal)
            .Trim();
    }

    private static string GetSimpleTypeName(string typeName)
    {
        var lastDotIndex = typeName.LastIndexOf('.');
        return lastDotIndex >= 0 ? typeName[(lastDotIndex + 1)..] : typeName;
    }
}

internal sealed record MethodParameter(string Type, string Name);
