namespace Incursa.Generators.AppDefinitions.Emission.PageFeatures;

using System.Text.RegularExpressions;
using Incursa.Generators.AppDefinitions.Config;
using Incursa.Generators.AppDefinitions.Model;
internal static partial class LegacyPageFeatureUtilities
{
    private const string ConfidentialBanner = "// CONFIDENTIAL - Copyright (c) PayeWaive LLC. All rights reserved.";
    private const string NoticeBanner = "// See NOTICE.md for full restrictions and usage terms.";
    private const string TenantScopeHandling = "StandardTenantRoute";
    private const string OrganizationScopeHandling = "StandardOrganizationRoute";

    public static string GetContractRootNamespace(ResolvedOutputTarget target)
    {
        return target.Namespace;
    }

    public static string GetContractFeatureNamespace(ResolvedOutputTarget target, PageFeatureDefinition feature)
    {
        return $"{target.Namespace}.{feature.Name}";
    }

    public static string GetLegacyScopeType(PageFeatureDefinition feature)
    {
        return feature.ScopeHandling switch
        {
            TenantScopeHandling => "ITenantScope",
            OrganizationScopeHandling => "IOrgScope",
            _ => "ISystemScope",
        };
    }

    public static string GetLegacyContextType(PageFeatureDefinition feature)
    {
        return feature.ScopeHandling switch
        {
            TenantScopeHandling => "TenantContext",
            OrganizationScopeHandling => "OrganizationContext",
            _ => "SystemContext",
        };
    }

    public static string GetLegacyRequestScopeAccessor(PageFeatureDefinition feature)
    {
        return feature.ScopeHandling switch
        {
            TenantScopeHandling => "TenantScope",
            OrganizationScopeHandling => "OrgScope",
            _ => "SystemScope",
        };
    }

    public static string GetLegacyContractTypeName(
        ResolvedOutputTarget target,
        PageFeatureDefinition feature,
        string rawType)
    {
        var contractRootNamespace = GetContractRootNamespace(target);
        var contractFeatureNamespace = GetContractFeatureNamespace(target, feature);
        var typeMap = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            [feature.ViewModelTypeName] = $"{contractRootNamespace}.{feature.ViewModelTypeName}",
        };

        foreach (var type in feature.OwnedTypes.Concat(feature.ApiModels))
        {
            typeMap[type.Name] = $"{contractFeatureNamespace}.{type.Name}";
        }

        return TypeTokenPattern().Replace(
            rawType,
            match =>
            {
                if (!typeMap.TryGetValue(match.Value, out var qualifiedTypeName))
                {
                    return match.Value;
                }

                return qualifiedTypeName;
            });
    }

    public static void AppendLegacySourceHeader(
        CodeBuilder builder,
        ApplicationDefinitionSet model,
        PageFeatureDefinition feature,
        bool enableNullable)
    {
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine(ConfidentialBanner);
        builder.AppendLine(NoticeBanner);
        builder.AppendLine($"// Generated from: {GetLegacyGeneratedFromPath(model, feature)}");
        if (enableNullable)
        {
            builder.AppendLine();
            builder.AppendLine("#nullable enable");
        }

        builder.AppendLine();
    }

    public static void AppendLegacyAutoGeneratedHeader(CodeBuilder builder)
    {
        builder.AppendLine("// <auto-generated/>");
    }

    public static void AppendLegacyPropertyDocumentation(CodeBuilder builder, PropertyDefinition property)
    {
        var verb = property.Settable ? "Gets or sets" : "Gets";
        builder.AppendLine("/// <summary>");
        builder.AppendLine($"/// {verb} the {property.Name} property.");
        builder.AppendLine("/// </summary>");
    }

    public static string BuildLegacyPropertyDeclaration(PropertyDefinition property, string typeName)
    {
        var accessor = property.Settable ? "set;" : "init;";
        var requiredModifier = property.Required ? "required " : string.Empty;
        return $"public {requiredModifier}{typeName} {property.Name} {{ get; {accessor} }}";
    }

    public static string ToLegacyParameterName(string value)
    {
        var pascalCase = EmitterUtilities.ToPascalCase(value);
        return string.IsNullOrEmpty(pascalCase)
            ? value
            : char.ToLowerInvariant(pascalCase[0]) + pascalCase[1..];
    }

    public static string BuildLegacyRoutePlaceholder(string parameterName)
    {
        return $"{{{ToLegacyParameterName(parameterName)}}}";
    }

    public static string BuildLegacyPageRoute(PageFeatureDefinition feature)
    {
        var route = (feature.Route ?? feature.Name).TrimStart('/');
        return feature.ScopeHandling switch
        {
            TenantScopeHandling => $"orgs/{{OrganizationId}}/tenants/{{TenantId}}/{route}",
            OrganizationScopeHandling => $"orgs/{{OrganizationId}}/{route}",
            _ => route,
        };
    }

    public static IReadOnlyList<MethodParameter> BuildLegacyUiEngineParameters(
        ResolvedOutputTarget contractTarget,
        PageFeatureDefinition feature,
        OperationDefinition? operation)
    {
        var seenParameterNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "scope",
        };
        var parameters = new List<MethodParameter>
        {
            new(GetLegacyScopeType(feature), "scope"),
        };

        foreach (var pageParameter in feature.PageParameters)
        {
            var parameterName = ToLegacyParameterName(pageParameter.Name);
            if (!seenParameterNames.Add(parameterName))
            {
                continue;
            }

            parameters.Add(new MethodParameter(
                FormatLegacyParameterType(pageParameter.Type, nullable: pageParameter.Source != PageParameterSource.Route && !pageParameter.Required),
                parameterName));
        }

        if (operation is null)
        {
            return parameters;
        }

        foreach (var parameter in OrderOperationParameters(operation.Parameters))
        {
            var parameterName = ToLegacyParameterName(parameter.Name);
            if (string.Equals(parameterName, "scope", StringComparison.Ordinal))
            {
                continue;
            }

            if (!seenParameterNames.Add(parameterName))
            {
                continue;
            }

            parameters.Add(new MethodParameter(
                GetLegacyContractTypeName(contractTarget, feature, FormatLegacyParameterType(parameter.Type, nullable: !parameter.Required)),
                parameterName));
        }

        foreach (var parameter in OrderOperationParameters(operation.RouteParameters))
        {
            var parameterName = ToLegacyParameterName(parameter.Name);
            if (!seenParameterNames.Add(parameterName))
            {
                continue;
            }

            parameters.Add(new MethodParameter(
                GetLegacyContractTypeName(contractTarget, feature, parameter.Type),
                parameterName));
        }

        foreach (var parameter in OrderOperationParameters(operation.QueryParameters))
        {
            var parameterName = ToLegacyParameterName(parameter.Name);
            if (!seenParameterNames.Add(parameterName))
            {
                continue;
            }

            parameters.Add(new MethodParameter(
                GetLegacyContractTypeName(contractTarget, feature, FormatLegacyParameterType(parameter.Type, nullable: !parameter.Required)),
                parameterName));
        }

        if (operation.BodyParameter is not null)
        {
            parameters.Add(new MethodParameter(
                GetLegacyContractTypeName(contractTarget, feature, operation.BodyParameter.Type),
                "payload"));
        }

        return parameters;
    }

    public static string GetLegacyOperationResultType(
        ResolvedOutputTarget contractTarget,
        PageFeatureDefinition feature,
        OperationDefinition? operation)
    {
        if (operation is null)
        {
            return GetLegacyContractTypeName(contractTarget, feature, feature.ViewModelTypeName);
        }

        var rawType = EmitterUtilities.GetOperationResultType(feature, operation);
        return string.IsNullOrWhiteSpace(rawType)
            ? "void"
            : GetLegacyContractTypeName(contractTarget, feature, rawType);
    }

    public static string FormatLegacyMethodSignature(IReadOnlyList<MethodParameter> parameters)
    {
        var parts = parameters.Select(static parameter => $"{parameter.Type} {parameter.Name}").ToList();
        if (!parameters.Any(static parameter => string.Equals(parameter.Name, "cancellationToken", StringComparison.OrdinalIgnoreCase)))
        {
            parts.Add("CancellationToken cancellationToken = default");
        }

        return string.Join(", ", parts);
    }

    public static bool IsTaskLikeReturnType(string typeName)
    {
        var rootTypeName = GetTopLevelTypeName(typeName);
        var simpleTypeName = GetSimpleTypeName(rootTypeName);
        return string.Equals(simpleTypeName, "Task", StringComparison.Ordinal)
            || string.Equals(simpleTypeName, "ValueTask", StringComparison.Ordinal);
    }

    public static string NormalizeTaskLikeReturnType(string typeName)
    {
        return typeName switch
        {
            "System.Threading.Tasks.Task" => "Task",
            "System.Threading.Tasks.ValueTask" => "ValueTask",
            _ => typeName
                .Replace("System.Threading.Tasks.Task<", "Task<", StringComparison.Ordinal)
                .Replace("System.Threading.Tasks.ValueTask<", "ValueTask<", StringComparison.Ordinal),
        };
    }

    private static IReadOnlyList<OperationParameterDefinition> OrderOperationParameters(IReadOnlyList<OperationParameterDefinition> parameters)
    {
        return parameters
            .OrderBy(static parameter => parameter.Location.Line)
            .ThenBy(static parameter => parameter.Location.Column)
            .ThenBy(static parameter => parameter.Name, StringComparer.Ordinal)
            .ToArray();
    }

    private static string FormatLegacyParameterType(string rawType, bool nullable)
    {
        if (!nullable || rawType.EndsWith("?", StringComparison.Ordinal))
        {
            return rawType;
        }

        return $"{rawType}?";
    }

    private static string GetTopLevelTypeName(string rawType)
    {
        return rawType
            .Split(['<', '[', '(', ','], StringSplitOptions.TrimEntries)[0]
            .Replace("global::", string.Empty, StringComparison.Ordinal)
            .Trim();
    }

    private static string GetSimpleTypeName(string typeName)
    {
        var lastDotIndex = typeName.LastIndexOf('.');
        return lastDotIndex >= 0 ? typeName[(lastDotIndex + 1)..] : typeName;
    }

    private static string GetLegacyGeneratedFromPath(ApplicationDefinitionSet model, PageFeatureDefinition feature)
    {
        var definitionRoot = Path.GetFullPath(model.DefinitionRootPath);
        var definitionRootParent = Directory.GetParent(definitionRoot)?.FullName;
        if (!string.IsNullOrWhiteSpace(definitionRootParent))
        {
            var relativeFromParent = Path.GetRelativePath(definitionRootParent, feature.SourceFilePath);
            var normalizedRelativeFromParent = EmitterUtilities.NormalizeRelativePath(relativeFromParent);
            return string.Equals(Path.GetFileName(definitionRootParent), "src", StringComparison.OrdinalIgnoreCase)
                ? $"/src/{normalizedRelativeFromParent}"
                : $"/{normalizedRelativeFromParent}";
        }

        var relativeFromRoot = Path.GetRelativePath(definitionRoot, feature.SourceFilePath);
        return $"/{EmitterUtilities.NormalizeRelativePath(relativeFromRoot)}";
    }

    [GeneratedRegex(@"(?<![\w.])([A-Za-z_][A-Za-z0-9_]*)(?![\w.])", RegexOptions.CultureInvariant)]
    private static partial Regex TypeTokenPattern();
}
