namespace Incursa.Generators.AppDefinitions.Emission.PageFeatures;

using Incursa.Generators.AppDefinitions.Config;
using Incursa.Generators.AppDefinitions.Diagnostics;
using Incursa.Generators.AppDefinitions.Model;
using Incursa.Generators.AppDefinitions.Pipeline;

public sealed class LegacyPageRegistrationHelperEmitter : IGenerationTargetEmitter
{
    public string Kind => "page-registration-helper-legacy";

    public IReadOnlyList<GeneratedFile> Emit(
        ResolvedOutputTarget target,
        ApplicationDefinitionSet model,
        FeatureFilter filter,
        DiagnosticBag diagnostics)
    {
        if (!string.IsNullOrWhiteSpace(filter.RawPattern))
        {
            return [];
        }

        var relativePath = "UiEngineServiceCollectionExtensions.g.cs";
        var absolutePath = EmitterUtilities.BuildAbsolutePath(target, relativePath);
        var uiEngineNamespace = EmitterUtilities.ResolveImportNamespace(target, "uiEngines");
        var implementationNamespace = EmitterUtilities.ResolveImportNamespace(target, "implementations");
        var builder = new CodeBuilder();

        LegacyPageFeatureUtilities.AppendLegacyAutoGeneratedHeader(builder);
        builder.AppendLine($"namespace {target.Namespace};");
        builder.AppendLine();
        builder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        builder.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        if (!string.Equals(uiEngineNamespace, target.Namespace, StringComparison.Ordinal))
        {
            builder.AppendLine($"using {uiEngineNamespace};");
        }

        if (!string.Equals(implementationNamespace, target.Namespace, StringComparison.Ordinal)
            && !string.Equals(implementationNamespace, uiEngineNamespace, StringComparison.Ordinal))
        {
            builder.AppendLine($"using {implementationNamespace};");
        }

        builder.AppendLine();
        builder.AppendLine("public static class UiEngineServiceCollectionExtensions");
        builder.AppendLine("{");
        using (builder.Indent())
        {
            builder.AppendLine("public static IServiceCollection AddUiEngines(this IServiceCollection services)");
            builder.AppendLine("{");
            using (builder.Indent())
            {
                foreach (var feature in model.PageFeatures.OrderBy(static feature => feature.Name, StringComparer.Ordinal))
                {
                    builder.AppendLine($"services.TryAddScoped<{uiEngineNamespace}.I{feature.Name}UiEngine, {implementationNamespace}.{feature.Name}UiEngine>();");
                }

                builder.AppendLine();
                builder.AppendLine("return services;");
            }

            builder.AppendLine("}");
        }

        builder.AppendLine("}");
        return [new GeneratedFile(target.Name, Kind, absolutePath, relativePath, builder.ToString())];
    }
}
