namespace Incursa.Generators.AppDefinitions.Emission.PageFeatures;

using Incursa.Generators.AppDefinitions.Config;
using Incursa.Generators.AppDefinitions.Diagnostics;
using Incursa.Generators.AppDefinitions.Model;
using Incursa.Generators.AppDefinitions.Pipeline;

public sealed class LegacyPageRouteHelperEmitter : IGenerationTargetEmitter
{
    public string Kind => "page-route-helper-legacy";

    public IReadOnlyList<GeneratedFile> Emit(
        ResolvedOutputTarget target,
        ApplicationDefinitionSet model,
        FeatureFilter filter,
        DiagnosticBag diagnostics)
    {
        if (!string.IsNullOrWhiteSpace(filter.RawPattern))
        {
            return [];
        }

        var pageFeatures = model.PageFeatures
            .Where(static feature => feature.SourceFilePath.EndsWith(".page.xml", StringComparison.OrdinalIgnoreCase))
            .OrderBy(static feature => feature.Name, StringComparer.Ordinal)
            .ToArray();

        var relativePath = "PageRoutes.g.cs";
        var absolutePath = EmitterUtilities.BuildAbsolutePath(target, relativePath);
        var builder = new CodeBuilder();

        LegacyPageFeatureUtilities.AppendLegacyAutoGeneratedHeader(builder);
        builder.AppendLine($"namespace {target.Namespace};");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Linq;");
        builder.AppendLine("using Flurl;");
        builder.AppendLine("using PayeWaive;");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// Defines constants for page routes and provides helper methods to build URLs.");
        builder.AppendLine("/// </summary>");
        builder.AppendLine("public static partial class PageRoutes");
        builder.AppendLine("{");
        using (builder.Indent())
        {
            builder.AppendLine("// --- Route Parameter Constants ---");
            foreach (var parameter in GetRouteConstants(pageFeatures))
            {
                builder.AppendLine($"public const string {parameter.Name}Param = \"{parameter.Placeholder}\";");
            }

            if (pageFeatures.Length > 0)
            {
                builder.AppendLine();
            }

            builder.AppendLine("// --- Route String Constants ---");
            foreach (var feature in pageFeatures)
            {
                builder.AppendLine($"public const string {feature.Name}Route = \"/{LegacyPageFeatureUtilities.BuildLegacyPageRoute(feature)}\";");
            }

            if (pageFeatures.Length > 0)
            {
                builder.AppendLine();
            }

            builder.AppendLine("// --- URL Builder Methods ---");
            foreach (var feature in pageFeatures)
            {
                EmitRouteMethod(builder, feature);
                builder.AppendLine();
            }
        }

        builder.AppendLine("}");
        return [new GeneratedFile(target.Name, Kind, absolutePath, relativePath, builder.ToString())];
    }

    private static IEnumerable<(string Name, string Placeholder)> GetRouteConstants(IEnumerable<PageFeatureDefinition> features)
    {
        yield return ("OrganizationId", "{organizationId}");
        yield return ("TenantId", "{tenantId}");

        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var feature in features)
        {
            foreach (var parameter in feature.PageParameters.Where(static parameter => parameter.Source == PageParameterSource.Route))
            {
                var constantName = EmitterUtilities.ToPascalCase(parameter.Name);
                if (!seen.Add(constantName))
                {
                    continue;
                }

                yield return (constantName, LegacyPageFeatureUtilities.BuildLegacyRoutePlaceholder(parameter.Name));
            }
        }
    }

    private static void EmitRouteMethod(CodeBuilder builder, PageFeatureDefinition feature)
    {
        var methodParameters = new List<string>();
        if (string.Equals(feature.ScopeHandling, "StandardTenantRoute", StringComparison.Ordinal))
        {
            methodParameters.Add("PayeWaive.OrganizationIdentifier organizationId");
            methodParameters.Add("PayeWaive.PayeWaiveTenantIdentifier tenantId");
        }
        else if (string.Equals(feature.ScopeHandling, "StandardOrganizationRoute", StringComparison.Ordinal))
        {
            methodParameters.Add("PayeWaive.OrganizationIdentifier organizationId");
        }

        methodParameters.AddRange(feature.PageParameters.Select(
            static parameter =>
            {
                var typeName = EmitterUtilities.FormatTypeName(parameter.Type, nullable: parameter.Source != PageParameterSource.Route && !parameter.Required);
                return $"{typeName} {LegacyPageFeatureUtilities.ToLegacyParameterName(parameter.Name)}";
            }));

        builder.AppendLine($"/// <summary>Builds the URL for the {feature.Name} page.</summary>");
        builder.AppendLine($"public static Url Get{feature.Name}Url({string.Join(", ", methodParameters)})");
        builder.AppendLine("{");
        using (builder.Indent())
        {
            builder.AppendLine($"string url = {feature.Name}Route;");
            if (string.Equals(feature.ScopeHandling, "StandardTenantRoute", StringComparison.Ordinal))
            {
                builder.AppendLine("url = url.Replace(OrganizationIdParam, organizationId.ToString(), StringComparison.OrdinalIgnoreCase);");
                builder.AppendLine("url = url.Replace(TenantIdParam, tenantId.ToString(), StringComparison.OrdinalIgnoreCase);");
            }
            else if (string.Equals(feature.ScopeHandling, "StandardOrganizationRoute", StringComparison.Ordinal))
            {
                builder.AppendLine("url = url.Replace(OrganizationIdParam, organizationId.ToString(), StringComparison.OrdinalIgnoreCase);");
            }

            foreach (var parameter in feature.PageParameters.Where(static parameter => parameter.Source == PageParameterSource.Route))
            {
                var parameterName = LegacyPageFeatureUtilities.ToLegacyParameterName(parameter.Name);
                builder.AppendLine($"url = url.Replace({EmitterUtilities.ToPascalCase(parameter.Name)}Param, {parameterName}.ToString(), StringComparison.OrdinalIgnoreCase);");
            }

            foreach (var parameter in feature.PageParameters.Where(static parameter => parameter.Source == PageParameterSource.Query))
            {
                var parameterName = LegacyPageFeatureUtilities.ToLegacyParameterName(parameter.Name);
                builder.AppendLine($"url = url.SetQueryParam(\"{parameter.Name}\", {parameterName});");
            }

            builder.AppendLine("return new Url(url);");
        }

        builder.AppendLine("}");
    }
}
