// <auto-generated/>
// CONFIDENTIAL - Copyright (c) Bravellian LLC. All rights reserved.
// See NOTICE.md for full restrictions and usage terms.

#nullable enable

namespace Bravellian;

using System;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;

[TypeConverter(typeof(PwCsTypeTypeConverter))]
public readonly partial record struct PwCsType
        : IComparable,
          IComparable<PwCsType>,
          IEquatable<PwCsType>
{
    private PwCsType(string value)
    {
        this.Value = value;
        ProcessValue(value, out bool isnullable);
        this.IsNullable = isnullable;
    }

    public string Value { get; }

    public bool IsNullable { get; }

    private static partial void ProcessValue(string value, out bool isnullable);

    public override string ToString() => this.Value;

    public bool Equals(PwCsType other)
    {
        return string.Equals(this.Value, other.Value);
    }

    public override int GetHashCode()
    {
        return this.Value?.GetHashCode() ?? 0;
    }

    public int CompareTo(PwCsType other)
    {
        return string.Compare(this.Value, other.Value);
    }

    public int CompareTo(object? obj)
    {
        return obj is PwCsType id ? this.Value.CompareTo(id.Value) : this.Value.CompareTo(obj);
    }

    public static bool TryParse(string? value, out PwCsType result)
    {
        if (value == null)
        {
            throw new ArgumentNullException(nameof(value));
        }

        result = new PwCsType(value);
        return true;
    }

    public static PwCsType? TryParse(string? value)
    {
        if (value == null)
        {
            return null;
        }

        if (PwCsType.TryParse(value, out PwCsType result))
        {
            return result;
        }

        return null;
    }

    public static PwCsType Parse(string value)
    {
        if (value == null)
        {
            throw new ArgumentNullException(nameof(value));
        }

        return new PwCsType(value);
    }

    // TypeConverter for PwCsType to and from string
    public class PwCsTypeTypeConverter : TypeConverter
    {
        public override bool CanConvertFrom(ITypeDescriptorContext? context, Type sourceType) =>
            sourceType == typeof(string) || base.CanConvertFrom(context, sourceType);

        public override bool CanConvertTo(ITypeDescriptorContext? context, Type? destinationType) =>
            destinationType == typeof(string) || base.CanConvertTo(context, destinationType);

        public override object? ConvertFrom(ITypeDescriptorContext? context, CultureInfo? culture, object value)
        {
            if (value is string s)
            {
                return PwCsType.Parse(s);
            }

            return base.ConvertFrom(context, culture, value);
        }

        public override object? ConvertTo(ITypeDescriptorContext? context, CultureInfo? culture, object? value, Type destinationType)
        {
            if (value is PwCsType type && destinationType == typeof(string))
            {
                return type.ToString();
            }

            return base.ConvertTo(context, culture, value, destinationType);
        }
    }
}

