// <auto-generated/>
// CONFIDENTIAL - Copyright (c) Bravellian LLC. All rights reserved.
// See NOTICE.md for full restrictions and usage terms.

#nullable enable

namespace Bravellian;

using System;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using Bravellian.Generators.SqlGen.Common;

public readonly partial record struct PwCsType
{
    public static readonly PwCsType String = new PwCsType("string");
    public static readonly PwCsType Int = new PwCsType("int");
    public static readonly PwCsType Long = new PwCsType("long");
    public static readonly PwCsType Guid = new PwCsType("Guid");
    public static readonly PwCsType Decimal = new PwCsType("decimal");
    public static readonly PwCsType Double = new PwCsType("double");
    public static readonly PwCsType Float = new PwCsType("float");
    public static readonly PwCsType Boolean = new PwCsType("bool");
    public static readonly PwCsType Byte = new PwCsType("byte");
    public static readonly PwCsType Short = new PwCsType("short");
    public static readonly PwCsType Char = new PwCsType("char");
    public static readonly PwCsType DateOnly = new PwCsType("DateOnly");
    public static readonly PwCsType DateTime = new PwCsType("DateTime");
    public static readonly PwCsType DateTimeOffset = new PwCsType("DateTimeOffset");
    public static readonly PwCsType Object = new PwCsType("object");
    public static readonly PwCsType ByteArray = new PwCsType("byte[]");
    public static readonly PwCsType TimeOnly = new PwCsType("TimeOnly");

    public static readonly PwCsType SpecialIdentifier = new PwCsType("special:identifier");
    public static readonly PwCsType SpecialErpIdentifier = new PwCsType("special:erpidentifier");
    public static readonly PwCsType SpecialColumnErpIdentifier = new PwCsType("special:columnerpidentifier");
    public static readonly PwCsType Unknown = new PwCsType("unknown");

    public static PwCsType FromCoreType(PwSqlType sqlType)
    {
        return FromCoreType(sqlType.CoreType);
    }

    public static PwCsType FromCoreType(SqlCoreType coreType)
    {
        return coreType switch
        {
            // Integer types
            SqlCoreType.Int => Int,
            SqlCoreType.BigInt => Long,
            SqlCoreType.SmallInt => Short,
            SqlCoreType.TinyInt => Byte,

            // Decimal types
            SqlCoreType.Decimal => Decimal,
            SqlCoreType.Numeric => Decimal,
            SqlCoreType.Money => Decimal,
            SqlCoreType.SmallMoney => Decimal,

            // Floating point types
            SqlCoreType.Float => Double,
            SqlCoreType.Real => Float,

            // String types
            SqlCoreType.Char => String,
            SqlCoreType.NChar => String,
            SqlCoreType.VarChar => String,
            SqlCoreType.NVarChar => String,
            SqlCoreType.Text => String,
            SqlCoreType.NText => String,

            // Binary types
            SqlCoreType.Binary => ByteArray,
            SqlCoreType.VarBinary => ByteArray,
            SqlCoreType.Image => ByteArray,

            // Date and time types
            SqlCoreType.Date => DateOnly,
            SqlCoreType.Time => TimeOnly,
            SqlCoreType.DateTime => DateTime,
            SqlCoreType.DateTime2 => DateTime,
            SqlCoreType.DateTimeOffset => DateTimeOffset,
            SqlCoreType.SmallDateTime => DateTime,

            // Other types
            SqlCoreType.Bit => Boolean,
            SqlCoreType.UniqueIdentifier => Guid,
            SqlCoreType.Xml => String,
            SqlCoreType.HierarchyId => String,
            SqlCoreType.Geography => Object,
            SqlCoreType.Geometry => Object,

            // Default case
            SqlCoreType.Unknown => Unknown,
            _ => Unknown
        };
    }

    private static partial void ProcessValue(string value, out bool isnullable)
    {
        // Check if the value ends with "?"
        isnullable = value.EndsWith("?");
    }
}

