// <auto-generated/>
// CONFIDENTIAL - Copyright (c) Bravellian LLC. All rights reserved.
// See NOTICE.md for full restrictions and usage terms.

#nullable enable

namespace Bravellian;

using System;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using Bravellian.Generators.SqlGen.Common;

[TypeConverter(typeof(PwSqlTypeTypeConverter))]
public readonly partial record struct PwSqlType
        : IComparable,
          IComparable<PwSqlType>,
          IEquatable<PwSqlType>
{
    private PwSqlType(string value)
    {
        PreProcessValue(value, out string newValue);
        this.Value = newValue;
        ProcessValue(newValue, out SqlCoreType coretype);
        this.CoreType = coretype;
    }

    public string Value { get; }

    public SqlCoreType CoreType { get; }

    private static partial void PreProcessValue(string value, out string newValue);

    private static partial void ProcessValue(string value, out SqlCoreType coretype);

    public override string ToString() => this.Value;

    public bool Equals(PwSqlType other)
    {
        return string.Equals(this.Value, other.Value);
    }

    public override int GetHashCode()
    {
        return this.Value?.GetHashCode() ?? 0;
    }

    public int CompareTo(PwSqlType other)
    {
        return string.Compare(this.Value, other.Value);
    }

    public int CompareTo(object? obj)
    {
        return obj is PwSqlType id ? this.Value.CompareTo(id.Value) : this.Value.CompareTo(obj);
    }

    //public static bool TryParse(string? value, out PwSqlType result)
    //{
    //    if (value == null)
    //    {
    //        throw new ArgumentNullException(nameof(value));
    //    }

    //    result = new PwSqlType(value);
    //    return true;
    //}

    //public static PwSqlType? TryParse(string? value)
    //{
    //    if (value == null)
    //    {
    //        return null;
    //    }

    //    if (PwSqlType.TryParse(value, out PwSqlType result))
    //    {
    //        return result;
    //    }

    //    return null;
    //}

    //public static PwSqlType Parse(string value)
    //{
    //    if (value == null)
    //    {
    //        throw new ArgumentNullException(nameof(value));
    //    }

    //    return new PwSqlType(value);
    //}

    public static PwSqlType GenerateRandom()
    {
        return new PwSqlType(Guid.NewGuid().ToString("N"));
    }

    // TypeConverter for PwSqlType to and from string
    public class PwSqlTypeTypeConverter : TypeConverter
    {
        public override bool CanConvertFrom(ITypeDescriptorContext? context, Type sourceType) =>
            sourceType == typeof(string) || base.CanConvertFrom(context, sourceType);

        public override bool CanConvertTo(ITypeDescriptorContext? context, Type? destinationType) =>
            destinationType == typeof(string) || base.CanConvertTo(context, destinationType);

        public override object? ConvertFrom(ITypeDescriptorContext? context, CultureInfo? culture, object value)
        {
            if (value is string s)
            {
                return PwSqlType.Parse(s);
            }

            return base.ConvertFrom(context, culture, value);
        }

        public override object? ConvertTo(ITypeDescriptorContext? context, CultureInfo? culture, object? value, Type destinationType)
        {
            if (value is PwSqlType type && destinationType == typeof(string))
            {
                return type.ToString();
            }

            return base.ConvertTo(context, culture, value, destinationType);
        }
    }
}

