// <auto-generated/>
// CONFIDENTIAL - Copyright (c) Bravellian LLC. All rights reserved.
// See NOTICE.md for full restrictions and usage terms.

#nullable enable

namespace Bravellian;

using System;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using Microsoft.SqlServer.TransactSql.ScriptDom;
using Bravellian.Generators.SqlGen.Common;

public readonly partial record struct PwSqlType
{
    public static readonly PwSqlType Unknown = new PwSqlType("UNKNOWN_TYPE_ERROR");
    public static readonly PwSqlType UniqueIdentifier = new PwSqlType("UNIQUEIDENTIFIER");
    public static readonly PwSqlType BigInt = new PwSqlType("BIGINT");
    public static readonly PwSqlType Int = new PwSqlType("INT");
    public static readonly PwSqlType SmallInt = new PwSqlType("SMALLINT");
    public static readonly PwSqlType TinyInt = new PwSqlType("TINYINT");
    public static readonly PwSqlType Decimal = new PwSqlType("DECIMAL");
    public static readonly PwSqlType Decimal182 = new PwSqlType("DECIMAL(18,2)");
    public static readonly PwSqlType Numeric = new PwSqlType("NUMERIC");
    public static readonly PwSqlType Money = new PwSqlType("MONEY");
    public static readonly PwSqlType SmallMoney = new PwSqlType("SMALLMONEY");
    public static readonly PwSqlType Float = new PwSqlType("FLOAT");
    public static readonly PwSqlType Real = new PwSqlType("REAL");
    public static readonly PwSqlType Char = new PwSqlType("CHAR");
    public static readonly PwSqlType NChar = new PwSqlType("NCHAR");
    public static readonly PwSqlType VarChar = new PwSqlType("VARCHAR");
    public static readonly PwSqlType NVarChar = new PwSqlType("NVARCHAR");
    public static readonly PwSqlType VarCharMax = new PwSqlType("VARCHAR(MAX)");
    public static readonly PwSqlType NVarCharMax = new PwSqlType("NVARCHAR(MAX)");
    public static readonly PwSqlType Text = new PwSqlType("TEXT");
    public static readonly PwSqlType NText = new PwSqlType("NTEXT");
    public static readonly PwSqlType Binary = new PwSqlType("BINARY");
    public static readonly PwSqlType VarBinary = new PwSqlType("VARBINARY");
    public static readonly PwSqlType VarBinaryMax = new PwSqlType("VARBINARY(MAX)");
    public static readonly PwSqlType Image = new PwSqlType("IMAGE");
    public static readonly PwSqlType Date = new PwSqlType("DATE");
    public static readonly PwSqlType Time = new PwSqlType("TIME");
    public static readonly PwSqlType DateTime = new PwSqlType("DATETIME");
    public static readonly PwSqlType DateTime2 = new PwSqlType("DATETIME2");
    public static readonly PwSqlType DateTimeOffset = new PwSqlType("DATETIMEOFFSET");
    public static readonly PwSqlType SmallDateTime = new PwSqlType("SMALLDATETIME");
    public static readonly PwSqlType Bit = new PwSqlType("BIT");
    public static readonly PwSqlType Xml = new PwSqlType("XML");
    public static readonly PwSqlType HierarchyId = new PwSqlType("HIERARCHYID");
    public static readonly PwSqlType Geography = new PwSqlType("GEOGRAPHY");
    public static readonly PwSqlType Geometry = new PwSqlType("GEOMETRY");


    public static PwSqlType FromSqlDataTypeOption(SqlDataTypeOption sqlDataTypeOption)
    {
        return PwSqlType.Parse(sqlDataTypeOption.ToString().ToUpperInvariant());
    }

    private static partial void PreProcessValue(string value, out string newValue)
    {
        // More robust preprocessing to handle various SQL type formats
        var cleaned = value.Trim().ToUpperInvariant();
        
        // Remove square brackets if present (SQL Server quoted identifiers)
        cleaned = cleaned.Trim('[', ']');
        
        // Normalize spaces in parentheses - remove spaces around commas and parentheses
        if (cleaned.Contains('(') && cleaned.Contains(')'))
        {
            var parenStart = cleaned.IndexOf('(');
            var parenEnd = cleaned.LastIndexOf(')');
            if (parenStart >= 0 && parenEnd > parenStart)
            {
                var beforeParen = cleaned.Substring(0, parenStart);
                var insideParen = cleaned.Substring(parenStart + 1, parenEnd - parenStart - 1);
                var afterParen = cleaned.Substring(parenEnd + 1);
                
                // Remove spaces around commas and normalize
                var parts = insideParen.Split(',');
                for (int i = 0; i < parts.Length; i++)
                {
                    parts[i] = parts[i].Trim();
                }
                insideParen = string.Join(",", parts);
                
                cleaned = beforeParen + "(" + insideParen + ")" + afterParen;
            }
        }
        
        newValue = cleaned;
    }

    private static partial void ProcessValue(string value, out SqlCoreType coretype)
    {
        // Extract the base type by removing any precision/scale parameters
        string baseType = value.Split('(')[0].Trim().ToUpperInvariant();

        // Determine the core type based on the SQL type name
        coretype = baseType switch
        {
            /// <summary>
            /// Integer types.
            /// </summary>
            "INT" => SqlCoreType.Int,
            "BIGINT" => SqlCoreType.BigInt,
            "SMALLINT" => SqlCoreType.SmallInt,
            "TINYINT" => SqlCoreType.TinyInt,

            /// <summary>
            /// Decimal types.
            /// </summary>
            "DECIMAL" => SqlCoreType.Decimal,
            "NUMERIC" => SqlCoreType.Numeric,
            "MONEY" => SqlCoreType.Money,
            "SMALLMONEY" => SqlCoreType.SmallMoney,

            /// <summary>
            /// Floating point types.
            /// </summary>
            "FLOAT" => SqlCoreType.Float,
            "REAL" => SqlCoreType.Real,

            /// <summary>
            /// String types.
            /// </summary>
            "CHAR" => SqlCoreType.Char,
            "NCHAR" => SqlCoreType.NChar,
            "VARCHAR" => SqlCoreType.VarChar,
            "NVARCHAR" => SqlCoreType.NVarChar,
            "TEXT" => SqlCoreType.Text,
            "NTEXT" => SqlCoreType.NText,

            /// <summary>
            /// Binary types.
            /// </summary>
            "BINARY" => SqlCoreType.Binary,
            "VARBINARY" => SqlCoreType.VarBinary,
            "IMAGE" => SqlCoreType.Image,

            /// <summary>
            /// Date and time types.
            /// </summary>
            "DATE" => SqlCoreType.Date,
            "TIME" => SqlCoreType.Time,
            "DATETIME" => SqlCoreType.DateTime,
            "DATETIME2" => SqlCoreType.DateTime2,
            "DATETIMEOFFSET" => SqlCoreType.DateTimeOffset,
            "SMALLDATETIME" => SqlCoreType.SmallDateTime,

            /// <summary>
            /// Other types.
            /// </summary>
            "BIT" => SqlCoreType.Bit,
            "UNIQUEIDENTIFIER" => SqlCoreType.UniqueIdentifier,
            "XML" => SqlCoreType.Xml,
            "HIERARCHYID" => SqlCoreType.HierarchyId,
            "GEOGRAPHY" => SqlCoreType.Geography,
            "GEOMETRY" => SqlCoreType.Geometry,

            // Default to Unknown for any unrecognized types
            _ => SqlCoreType.Unknown
        };
    }

    /// <summary>
    /// Parses a SQL type string into a PwSqlType.
    /// </summary>
    /// <param name="sqlType">The SQL type string to parse.</param>
    /// <returns>The corresponding PwSqlType, or Unknown if not recognized.</returns>
    public static PwSqlType Parse(string sqlType)
    {
        if (string.IsNullOrWhiteSpace(sqlType))
        {
            return Unknown;
        }

        // Remove parameters (e.g., nvarchar(500) -> nvarchar)
        var normalized = sqlType.Trim();
        var parenIndex = normalized.IndexOf('(');
        if (parenIndex > 0)
        {
            normalized = normalized.Substring(0, parenIndex);
        }
        normalized = normalized.Trim().ToUpperInvariant();

        // Direct match for known types
        switch (normalized)
        {
            case "UNIQUEIDENTIFIER": return UniqueIdentifier;
            case "BIGINT": return BigInt;
            case "INT": return Int;
            case "SMALLINT": return SmallInt;
            case "TINYINT": return TinyInt;
            case "DECIMAL": return Decimal;
            case "NUMERIC": return Numeric;
            case "MONEY": return Money;
            case "SMALLMONEY": return SmallMoney;
            case "FLOAT": return Float;
            case "REAL": return Real;
            case "CHAR": return Char;
            case "NCHAR": return NChar;
            case "VARCHAR": return VarChar;
            case "NVARCHAR": return NVarChar;
            case "TEXT": return Text;
            case "NTEXT": return NText;
            case "BINARY": return Binary;
            case "VARBINARY": return VarBinary;
            case "IMAGE": return Image;
            case "DATE": return Date;
            case "TIME": return Time;
            case "DATETIME": return DateTime;
            case "DATETIME2": return DateTime2;
            case "DATETIMEOFFSET": return DateTimeOffset;
            case "SMALLDATETIME": return SmallDateTime;
            case "BIT": return Bit;
            case "XML": return Xml;
            case "HIERARCHYID": return HierarchyId;
            case "GEOGRAPHY": return Geography;
            case "GEOMETRY": return Geometry;
            default: return Unknown;
        }
    }
}

