// CONFIDENTIAL - Copyright (c) Incursa LLC. All rights reserved.
// See NOTICE.md for full restrictions and usage terms.

#nullable enable

namespace Incursa.Generators;

/// <summary>
/// Generates Entity Framework Core ValueConverter code for backed types.
/// </summary>
public static class ValueConverterGenerator
{
    /// <summary>
    /// Generates a ValueConverter for a FastId-backed type.
    /// </summary>
    public static string GenerateFastIdBackedConverter(string name, string namespaceName)
    {
        return $$"""
// <auto-generated/>
// CONFIDENTIAL - Copyright (c) Incursa LLC. All rights reserved.
// See NOTICE.md for full restrictions and usage terms.

#nullable enable

namespace {{namespaceName}};

using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

/// <summary>
/// Entity Framework Core value converter for {{name}}.
/// Converts between {{name}} and its underlying long database representation.
/// </summary>
public sealed class {{name}}ValueConverter : ValueConverter<{{name}}, long>
{
    /// <summary>
    /// Singleton instance of the converter.
    /// </summary>
    public static readonly {{name}}ValueConverter Instance = new();

    /// <summary>
    /// Initializes a new instance of the <see cref="{{name}}ValueConverter"/> class.
    /// </summary>
    public {{name}}ValueConverter()
        : base(
            model => model.Value.Value,
            database => {{name}}.From(database))
    {
    }
}

/// <summary>
/// Entity Framework Core value converter for {{name}}.
/// Converts between {{name}}? and its underlying long? database representation.
/// </summary>
public sealed class {{name}}NullableValueConverter : ValueConverter<{{name}}?, long?>
{
    /// <summary>
    /// Singleton instance of the converter.
    /// </summary>
    public static readonly {{name}}NullableValueConverter Instance = new();

    /// <summary>
    /// Initializes a new instance of the <see cref="{{name}}NullableValueConverter"/> class.
    /// </summary>
    public {{name}}NullableValueConverter()
        : base(
            model => model.HasValue ? model.Value.Value.Value : null,
            database => database.HasValue ? {{name}}.From(database.Value) : null)
    {
    }
}

""";
    }

    /// <summary>
    /// Generates a ValueConverter for a Guid-backed type.
    /// </summary>
    public static string GenerateGuidBackedConverter(string name, string namespaceName)
    {
        return $$"""
// <auto-generated/>
// CONFIDENTIAL - Copyright (c) Incursa LLC. All rights reserved.
// See NOTICE.md for full restrictions and usage terms.

#nullable enable

namespace {{namespaceName}};

using System;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

/// <summary>
/// Entity Framework Core value converter for {{name}}.
/// Converts between {{name}} and its underlying Guid database representation.
/// </summary>
public sealed class {{name}}ValueConverter : ValueConverter<{{name}}, Guid>
{
    /// <summary>
    /// Singleton instance of the converter.
    /// </summary>
    public static readonly {{name}}ValueConverter Instance = new();

    /// <summary>
    /// Initializes a new instance of the <see cref="{{name}}ValueConverter"/> class.
    /// </summary>
    public {{name}}ValueConverter()
        : base(
            model => model.Value,
            database => {{name}}.From(database))
    {
    }
}

/// <summary>
/// Entity Framework Core value converter for {{name}}.
/// Converts between {{name}}? and its underlying Guid? database representation.
/// </summary>
public sealed class {{name}}NullableValueConverter : ValueConverter<{{name}}?, Guid?>
{
    /// <summary>
    /// Singleton instance of the converter.
    /// </summary>
    public static readonly {{name}}NullableValueConverter Instance = new();

    /// <summary>
    /// Initializes a new instance of the <see cref="{{name}}NullableValueConverter"/> class.
    /// </summary>
    public {{name}}NullableValueConverter()
        : base(
            model => model.HasValue ? model.Value.Value.Value : null,
            database => database.HasValue ? {{name}}.From(database.Value) : null)
    {
    }
}

""";
    }

    /// <summary>
    /// Generates a ValueConverter for a string-backed type.
    /// </summary>
    public static string GenerateStringBackedConverter(string name, string namespaceName)
    {
        return $$"""
// <auto-generated/>
// CONFIDENTIAL - Copyright (c) Incursa LLC. All rights reserved.
// See NOTICE.md for full restrictions and usage terms.

#nullable enable

namespace {{namespaceName}};

using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

/// <summary>
/// Entity Framework Core value converter for {{name}}.
/// Converts between {{name}} and its underlying string database representation.
/// </summary>
public sealed class {{name}}ValueConverter : ValueConverter<{{name}}, string>
{
    /// <summary>
    /// Singleton instance of the converter.
    /// </summary>
    public static readonly {{name}}ValueConverter Instance = new();

    /// <summary>
    /// Initializes a new instance of the <see cref="{{name}}ValueConverter"/> class.
    /// </summary>
    public {{name}}ValueConverter()
        : base(
            model => model.Value,
            database => {{name}}.From(database))
    {
    }
}

/// <summary>
/// Entity Framework Core value converter for {{name}}.
/// Converts between {{name}}? and its underlying string? database representation.
/// </summary>
public sealed class {{name}}NullableValueConverter : ValueConverter<{{name}}?, string?>
{
    /// <summary>
    /// Singleton instance of the converter.
    /// </summary>
    public static readonly {{name}}NullableValueConverter Instance = new();

    /// <summary>
    /// Initializes a new instance of the <see cref="{{name}}NullableValueConverter"/> class.
    /// </summary>
    public {{name}}NullableValueConverter()
        : base(
            model => model.HasValue ? model.Value.Value : null,
            database => database != null ? {{name}}.From(database) : null)
    {
    }
}

""";
    }

    /// <summary>
    /// Generates a ValueConverter for a number-backed enum type.
    /// </summary>
    public static string GenerateNumberBackedEnumConverter(string name, string namespaceName, string numberType)
    {
        return $$"""
// <auto-generated/>
// CONFIDENTIAL - Copyright (c) Incursa LLC. All rights reserved.
// See NOTICE.md for full restrictions and usage terms.

#nullable enable

namespace {{namespaceName}};

using System;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

/// <summary>
/// Entity Framework Core value converter for {{name}}.
/// Converts between {{name}} and its underlying {{numberType}} database representation.
/// </summary>
public sealed class {{name}}ValueConverter : ValueConverter<{{name}}, {{numberType}}>
{
    /// <summary>
    /// Singleton instance of the converter.
    /// </summary>
    public static readonly {{name}}ValueConverter Instance = new();

    /// <summary>
    /// Initializes a new instance of the <see cref="{{name}}ValueConverter"/> class.
    /// </summary>
    public {{name}}ValueConverter()
        : base(
            model => model.Value,
            database => {{name}}.FromValue(database))
    {
    }
}

/// <summary>
/// Entity Framework Core value converter for {{name}}.
/// Converts between {{name}}? and its underlying {{numberType}}? database representation.
/// </summary>
public sealed class {{name}}NullableValueConverter : ValueConverter<{{name}}?, {{numberType}}?>
{
    /// <summary>
    /// Singleton instance of the converter.
    /// </summary>
    public static readonly {{name}}NullableValueConverter Instance = new();

    /// <summary>
    /// Initializes a new instance of the <see cref="{{name}}NullableValueConverter"/> class.
    /// </summary>
    public {{name}}NullableValueConverter()
        : base(
            model => model.HasValue ? model.Value.Value.Value : null,
            database => database.HasValue ? {{name}}.From(database.Value) : null)
    {
    }
}

""";
    }

    /// <summary>
    /// Generates a ValueConverter for a string-backed enum type.
    /// </summary>
    public static string GenerateStringBackedEnumConverter(string name, string namespaceName)
    {
        return $$"""
// <auto-generated/>
// CONFIDENTIAL - Copyright (c) Incursa LLC. All rights reserved.
// See NOTICE.md for full restrictions and usage terms.

#nullable enable

namespace {{namespaceName}};

using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

/// <summary>
/// Entity Framework Core value converter for {{name}}.
/// Converts between {{name}} and its underlying string database representation.
/// </summary>
public sealed class {{name}}ValueConverter : ValueConverter<{{name}}, string>
{
    /// <summary>
    /// Singleton instance of the converter.
    /// </summary>
    public static readonly {{name}}ValueConverter Instance = new();

    /// <summary>
    /// Initializes a new instance of the <see cref="{{name}}ValueConverter"/> class.
    /// </summary>
    public {{name}}ValueConverter()
        : base(
            model => model.Value,
            database => {{name}}.Parse(database))
    {
    }
}

/// <summary>
/// Entity Framework Core value converter for {{name}}.
/// Converts between {{name}}? and its underlying string? database representation.
/// </summary>
public sealed class {{name}}NullableValueConverter : ValueConverter<{{name}}?, string?>
{
    /// <summary>
    /// Singleton instance of the converter.
    /// </summary>
    public static readonly {{name}}NullableValueConverter Instance = new();

    /// <summary>
    /// Initializes a new instance of the <see cref="{{name}}NullableValueConverter"/> class.
    /// </summary>
    public {{name}}NullableValueConverter()
        : base(
            model => model.HasValue ? model.Value.Value : null,
            database => database != null ? {{name}}.From(database) : null)
    {
    }
}

""";
    }

    /// <summary>
    /// Generates a ValueConverter for a multi-value backed type.
    /// </summary>
    public static string GenerateMultiValueBackedConverter(string name, string namespaceName)
    {
        return $$"""
// <auto-generated/>
// CONFIDENTIAL - Copyright (c) Incursa LLC. All rights reserved.
// See NOTICE.md for full restrictions and usage terms.

#nullable enable

namespace {{namespaceName}};

using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

/// <summary>
/// Entity Framework Core value converter for {{name}}.
/// Converts between {{name}} and its underlying string database representation.
/// </summary>
public sealed class {{name}}ValueConverter : ValueConverter<{{name}}, string>
{
    /// <summary>
    /// Singleton instance of the converter.
    /// </summary>
    public static readonly {{name}}ValueConverter Instance = new();

    /// <summary>
    /// Initializes a new instance of the <see cref="{{name}}ValueConverter"/> class.
    /// </summary>
    public {{name}}ValueConverter()
        : base(
            model => model.Value,
            database => {{name}}.Parse(database))
    {
    }
}

/// <summary>
/// Entity Framework Core value converter for {{name}}.
/// Converts between {{name}}? and its underlying string? database representation.
/// </summary>
public sealed class {{name}}NullableValueConverter : ValueConverter<{{name}}?, string?>
{
    /// <summary>
    /// Singleton instance of the converter.
    /// </summary>
    public static readonly {{name}}NullableValueConverter Instance = new();

    /// <summary>
    /// Initializes a new instance of the <see cref="{{name}}NullableValueConverter"/> class.
    /// </summary>
    public {{name}}NullableValueConverter()
        : base(
            model => model.HasValue ? model.Value.Value : null,
            database => database != null ? {{name}}.From(database) : null)
    {
    }
}

""";
    }
}
