// <auto-generated />
// Generated by Incursa.Generators.Tool
// Command: incursa-appdefs
// Do not edit this file by hand. Your changes will be overwritten.
// Ownership: target=contracts; kind=page-contract-models; relative-path=Customer/CustomerListContracts.g.cs

#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Example.Contracts.Pages;

public partial class CustomerListViewModel
{
    public required IReadOnlyList<CustomerSummary> Items { get; init; }

    public required string Title { get; init; }

}

public partial class CustomerSummary
{
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    [JsonPropertyName("displayName")]
    public required string DisplayName { get; init; }

}

public partial class ArchiveCustomerRequest
{
    public required string Reason { get; init; }

}

public partial class ArchiveResult
{
    public required bool Success { get; init; }

}
