namespace Incursa.Generators.AppDefinitions.Tests;

using Incursa.Generators.AppDefinitions.Pipeline;
using Incursa.Generators.AppDefinitions.Tests.Fixtures;

public sealed class LegacyEmitterTests
{
    [Fact]
    public void Legacy_targets_emit_payewaive_compatible_surface()
    {
        using var workspace = new TestWorkspace();
        var configPath = workspace.WriteFile(
            "app-definitions.json",
            """
            {
              "version": 1,
              "definitionRoot": "defs",
              "definitionPatterns": [ "*.page.xml" ],
              "validation": {
                "knownTypeNames": [ "IReadOnlyList", "OrderId", "DocumentId", "WorkflowType", "JsonObject", "IOrgScope" ]
              },
              "targets": {
                "contracts": {
                  "kind": "page-contract-models-legacy",
                  "directory": "generated/contracts",
                  "namespace": "Example.Contracts"
                },
                "uiEngines": {
                  "kind": "page-ui-engine-interface-legacy",
                  "directory": "generated/ui-engines",
                  "namespace": "Example.UiEngines",
                  "imports": {
                    "contracts": "Example.Contracts"
                  }
                },
                "pageModelBases": {
                  "kind": "page-model-base-legacy",
                  "directory": "generated/page-models",
                  "namespace": "Example.Web.Pages",
                  "imports": {
                    "contracts": "Example.Contracts",
                    "uiEngines": "Example.UiEngines"
                  }
                },
                "registrations": {
                  "kind": "page-registration-helper-legacy",
                  "directory": "generated/registrations",
                  "namespace": "Example.Server",
                  "imports": {
                    "uiEngines": "Example.UiEngines",
                    "implementations": "Example.UiEngines"
                  }
                },
                "pageRoutes": {
                  "kind": "page-route-helper-legacy",
                  "directory": "generated/routes",
                  "namespace": "Example.Web"
                }
              }
            }
            """);

        workspace.WriteFile(
            Path.Combine("defs", "Sales", "OrderDetail.page.xml"),
            """
            <PageFeature name="OrderDetail" route="orders/{orderId}" scopeHandling="StandardTenantRoute">
              <PageParameters>
                <Parameter name="orderId" type="OrderId" source="Route" required="true" />
                <Parameter name="tab" type="string" source="Query" required="false" />
              </PageParameters>
              <ViewModelProperties>
                <Property name="Title" type="string" />
                <Property name="Items" type="IReadOnlyList&lt;LineItem&gt;" required="true" />
              </ViewModelProperties>
              <ViewModelOwnedType name="LineItem">
                <Property name="DisplayName" type="string" required="true" json-property="displayName" />
              </ViewModelOwnedType>
              <Operations>
                <Operation name="SaveAsyncOperation" returnType="System.Threading.Tasks.Task">
                  <Parameter name="scope" type="IOrgScope" />
                  <Parameter name="connectionString" type="string" />
                  <Parameter name="cancellationToken" type="System.Threading.CancellationToken" />
                </Operation>
                <Operation name="DeleteDocument">
                  <QueryParameter name="documentId" type="DocumentId" />
                </Operation>
                <Operation name="MatchTemplates">
                  <QueryParameter name="WorkflowType" type="WorkflowType" required="true" />
                  <QueryParameter name="Context" type="System.Text.Json.Nodes.JsonObject" required="true" />
                </Operation>
                <Operation name="ChangeStatus">
                  <QueryParameter name="status" type="string" required="true" />
                </Operation>
              </Operations>
            </PageFeature>
            """);

        var result = new AppDefinitionGenerator().Execute(new GenerationRequest(configPath), GenerationExecutionMode.Write);

        result.Success.ShouldBeTrue(string.Join(Environment.NewLine, result.Diagnostics));
        result.GeneratedFiles.Count.ShouldBe(6);

        var viewModel = File.ReadAllText(Path.Combine(workspace.RootPath, "generated", "contracts", "Sales", "OrderDetail", "OrderDetailViewModel.g.cs"));
        viewModel.ShouldContain("// <auto-generated/>");
        viewModel.ShouldContain("// Generated from: /defs/Sales/OrderDetail.page.xml");
        viewModel.ShouldContain("namespace Example.Contracts;");
        viewModel.ShouldContain("namespace Example.Contracts;");
        viewModel.ShouldContain("public partial record OrderDetailViewModel");
        viewModel.ShouldContain("/// Gets or sets the Title property.");
        viewModel.ShouldContain("[Required]");
        viewModel.ShouldContain("public required string Title { get; set; }");
        viewModel.ShouldContain("public required IReadOnlyList<Example.Contracts.OrderDetail.LineItem> Items { get; set; }");
        viewModel.ShouldNotContain("// Generated by Incursa.Generators.Tool");
        viewModel.ShouldNotContain("= default!;");

        var ownedType = File.ReadAllText(Path.Combine(workspace.RootPath, "generated", "contracts", "Sales", "OrderDetail", "LineItem.g.cs"));
        ownedType.ShouldContain("namespace Example.Contracts.OrderDetail;");

        var uiEngine = File.ReadAllText(Path.Combine(workspace.RootPath, "generated", "ui-engines", "Sales", "IOrderDetailUiEngine.g.cs"));
        uiEngine.ShouldContain("// Generated from: /defs/Sales/OrderDetail.page.xml");
        uiEngine.ShouldContain("using Example.Contracts; // Include VM namespace for types used in signatures");
        uiEngine.ShouldContain("/// UI Engine for OrderDetail feature.");
        uiEngine.ShouldContain("InitVmAsync(ITenantScope scope, OrderId orderId, string? tab, CancellationToken cancellationToken = default)");
        uiEngine.ShouldContain("ChangeStatusAsync(ITenantScope scope, OrderId orderId, string? tab, string status, CancellationToken cancellationToken = default)");
        uiEngine.ShouldContain("Task SaveAsyncOperationAsync(ITenantScope scope, OrderId orderId, string? tab, string connectionString, System.Threading.CancellationToken cancellationToken);");
        uiEngine.ShouldContain("DeleteDocumentAsync(ITenantScope scope, OrderId orderId, string? tab, DocumentId documentId, CancellationToken cancellationToken = default)");
        uiEngine.ShouldContain("MatchTemplatesAsync(ITenantScope scope, OrderId orderId, string? tab, WorkflowType workflowType, System.Text.Json.Nodes.JsonObject context, CancellationToken cancellationToken = default)");

        var pageModelBase = File.ReadAllText(Path.Combine(workspace.RootPath, "generated", "page-models", "Sales", "OrderDetailModelBase.g.cs"));
        pageModelBase.ShouldContain("// Generated from: /defs/Sales/OrderDetail.page.xml");
        pageModelBase.ShouldContain("public abstract class OrderDetailModelBase : PageModel");
        pageModelBase.ShouldContain("public ITenantScope Scope => this.PwRequestInfo.TenantScope;");

        var registrations = File.ReadAllText(Path.Combine(workspace.RootPath, "generated", "registrations", "UiEngineServiceCollectionExtensions.g.cs"));
        registrations.ShouldContain("// <auto-generated/>");
        registrations.ShouldContain("services.TryAddScoped<Example.UiEngines.IOrderDetailUiEngine, Example.UiEngines.OrderDetailUiEngine>();");

        var routes = File.ReadAllText(Path.Combine(workspace.RootPath, "generated", "routes", "PageRoutes.g.cs"));
        routes.ShouldContain("// <auto-generated/>");
        routes.ShouldContain("// --- Route Parameter Constants ---");
        routes.ShouldContain("public const string OrganizationIdParam = \"{organizationId}\";");
        routes.ShouldContain("/// <summary>Builds the URL for the OrderDetail page.</summary>");
        routes.ShouldContain("public const string OrderDetailRoute = \"/orgs/{OrganizationId}/tenants/{TenantId}/orders/{orderId}\";");
        routes.ShouldContain("url = url.SetQueryParam(\"tab\", tab);");
    }

    [Fact]
    public void Legacy_ui_engine_preserves_declared_parameter_shape()
    {
        using var workspace = new TestWorkspace();
        var configPath = workspace.WriteFile(
            "app-definitions.json",
            """
            {
              "version": 1,
              "definitionRoot": "defs",
              "definitionPatterns": [ "*.page.xml" ],
              "validation": {
                "knownTypeNames": [ "IOrgScope", "BillingPeriodIdentifier", "PhoneNumber" ]
              },
              "targets": {
                "contracts": {
                  "kind": "page-contract-models-legacy",
                  "directory": "generated/contracts",
                  "namespace": "Example.Contracts"
                },
                "uiEngines": {
                  "kind": "page-ui-engine-interface-legacy",
                  "directory": "generated/ui-engines",
                  "namespace": "Example.UiEngines",
                  "imports": {
                    "contracts": "Example.Contracts"
                  }
                }
              }
            }
            """);

        workspace.WriteFile(
            Path.Combine("defs", "Settings.page.xml"),
            """
            <PageFeature name="Settings" scopeHandling="StandardOrganizationRoute">
              <PageParameters>
                <Parameter name="periodId" type="BillingPeriodIdentifier" source="Query" required="false" />
              </PageParameters>
              <ViewModelProperties>
                <Property name="Title" type="string" required="true" />
              </ViewModelProperties>
              <Operations>
                <Operation name="OrderedSearch">
                  <QueryParameter name="searchTerm" type="string" required="false" />
                  <QueryParameter name="maxResults" type="int" required="false" />
                  <QueryParameter name="workspaceId" type="string" />
                </Operation>
                <Operation name="SaveConnectionString" returnType="System.Threading.Tasks.Task">
                  <Parameter name="scope" type="IOrgScope" />
                  <Parameter name="connectionString" type="string" />
                  <Parameter name="cancellationToken" type="System.Threading.CancellationToken" default="default" />
                </Operation>
                <Operation name="UpdatePhone">
                  <QueryParameter name="phone" type="PhoneNumber" required="false" />
                </Operation>
              </Operations>
            </PageFeature>
            """);

        var result = new AppDefinitionGenerator().Execute(new GenerationRequest(configPath), GenerationExecutionMode.Write);

        result.Success.ShouldBeTrue(string.Join(Environment.NewLine, result.Diagnostics));

        var uiEngine = File.ReadAllText(Path.Combine(workspace.RootPath, "generated", "ui-engines", "ISettingsUiEngine.g.cs"));
        uiEngine.ShouldContain("InitVmAsync(IOrgScope scope, BillingPeriodIdentifier? periodId, CancellationToken cancellationToken = default)");
        uiEngine.ShouldContain("OrderedSearchAsync(IOrgScope scope, BillingPeriodIdentifier? periodId, string? searchTerm, int? maxResults, string workspaceId, CancellationToken cancellationToken = default)");
        uiEngine.ShouldContain("Task SaveConnectionStringAsync(IOrgScope scope, BillingPeriodIdentifier? periodId, string connectionString, System.Threading.CancellationToken cancellationToken);");
        uiEngine.ShouldContain("UpdatePhoneAsync(IOrgScope scope, BillingPeriodIdentifier? periodId, PhoneNumber? phone, CancellationToken cancellationToken = default)");
        uiEngine.ShouldNotContain("Task<System.Threading.Tasks.Task>");
        uiEngine.ShouldNotContain("cancellationToken, CancellationToken cancellationToken");
    }

    [Fact]
    public void Legacy_route_helpers_treat_route_page_parameters_as_required_by_default()
    {
        using var workspace = new TestWorkspace();
        var configPath = workspace.WriteFile(
            "app-definitions.json",
            """
            {
              "version": 1,
              "definitionRoot": "defs",
              "definitionPatterns": [ "*.page.xml" ],
              "validation": {
                "knownTypeNames": [ "ShortCode" ]
              },
              "targets": {
                "pageRoutes": {
                  "kind": "page-route-helper-legacy",
                  "directory": "generated/routes",
                  "namespace": "Example.Web"
                }
              }
            }
            """);

        workspace.WriteFile(
            Path.Combine("defs", "AnonymousPayAppEntry.page.xml"),
            """
            <PageDefinition name="AnonymousPayAppEntry" route="a/payapps/{code}" scopeHandling="AnonymousRoute" allowAnonymous="true">
              <PageParameters>
                <Parameter name="code" type="ShortCode" source="Route" />
              </PageParameters>
            </PageDefinition>
            """);

        var result = new AppDefinitionGenerator().Execute(new GenerationRequest(configPath), GenerationExecutionMode.Write);

        result.Success.ShouldBeTrue(string.Join(Environment.NewLine, result.Diagnostics));

        var routes = File.ReadAllText(Path.Combine(workspace.RootPath, "generated", "routes", "PageRoutes.g.cs"));
        routes.ShouldContain("public const string CodeParam = \"{code}\";");
        routes.ShouldContain("public static Url GetAnonymousPayAppEntryUrl(ShortCode code)");
        routes.ShouldContain("url = url.Replace(CodeParam, code.ToString(), StringComparison.OrdinalIgnoreCase);");
        routes.ShouldNotContain("ShortCode? code");
        routes.ShouldNotContain("#nullable enable");
    }
}
