namespace Incursa.Generators.AppDefinitions.Tests;

using Incursa.Generators.AppDefinitions.Tests.Fixtures;
using Incursa.Generators.Tool.Console;

public sealed class WriteModeCleanupTests
{
    [Fact]
    public async Task Cli_generate_write_deletes_owned_orphan_files()
    {
        using var workspace = new TestWorkspace();
        workspace.CopyDirectory(TestWorkspace.GetTestDataPath("HappyPath", "Source"));

        var configPath = Path.Combine(workspace.RootPath, "app-definitions.json");
        await ToolCommandRunner.RunAsync(
            ["generate", "--config", configPath, "--write"],
            TextWriter.Null,
            TextWriter.Null,
            TestContext.Current.CancellationToken);

        var orphanPath = Path.Combine(workspace.RootPath, "generated", "contracts", "Customer", "OldContracts.g.cs");
        File.WriteAllText(
            orphanPath,
            """
            // <auto-generated />
            // Generated by Incursa.Generators.Tool
            // Command: incursa-appdefs
            // Do not edit this file by hand. Your changes will be overwritten.
            // Ownership: target=contracts; kind=page-contract-models; relative-path=Customer/OldContracts.g.cs

            #nullable enable
            """);

        var exitCode = await ToolCommandRunner.RunAsync(
            ["generate", "--config", configPath, "--write"],
            TextWriter.Null,
            TextWriter.Null,
            TestContext.Current.CancellationToken);

        exitCode.ShouldBe(0);
        File.Exists(orphanPath).ShouldBeFalse();
    }

    [Fact]
    public async Task Cli_generate_write_does_not_delete_non_owned_files()
    {
        using var workspace = new TestWorkspace();
        workspace.CopyDirectory(TestWorkspace.GetTestDataPath("HappyPath", "Source"));

        var configPath = Path.Combine(workspace.RootPath, "app-definitions.json");
        await ToolCommandRunner.RunAsync(
            ["generate", "--config", configPath, "--write"],
            TextWriter.Null,
            TextWriter.Null,
            TestContext.Current.CancellationToken);

        var manualPath = Path.Combine(workspace.RootPath, "generated", "contracts", "Customer", "ManualKeep.g.cs");
        File.WriteAllText(manualPath, "// handwritten file");

        var exitCode = await ToolCommandRunner.RunAsync(
            ["generate", "--config", configPath, "--write"],
            TextWriter.Null,
            TextWriter.Null,
            TestContext.Current.CancellationToken);

        exitCode.ShouldBe(0);
        File.Exists(manualPath).ShouldBeTrue();
    }

    [Fact]
    public async Task Cli_generate_write_removes_files_for_deleted_definitions()
    {
        using var workspace = new TestWorkspace();
        workspace.CopyDirectory(TestWorkspace.GetTestDataPath("HappyPath", "Source"));

        var configPath = Path.Combine(workspace.RootPath, "app-definitions.json");
        await ToolCommandRunner.RunAsync(
            ["generate", "--config", configPath, "--write"],
            TextWriter.Null,
            TextWriter.Null,
            TestContext.Current.CancellationToken);

        File.Delete(Path.Combine(workspace.RootPath, "defs", "Customer", "CustomerList.page.xml"));

        var exitCode = await ToolCommandRunner.RunAsync(
            ["generate", "--config", configPath, "--write"],
            TextWriter.Null,
            TextWriter.Null,
            TestContext.Current.CancellationToken);

        exitCode.ShouldBe(0);
        File.Exists(Path.Combine(workspace.RootPath, "generated", "contracts", "Customer", "CustomerListContracts.g.cs")).ShouldBeFalse();
        File.Exists(Path.Combine(workspace.RootPath, "generated", "ui-engines", "Customer", "ICustomerListUiEngine.g.cs")).ShouldBeFalse();
        File.Exists(Path.Combine(workspace.RootPath, "generated", "page-models", "Customer", "CustomerListPageModelBase.g.cs")).ShouldBeFalse();
        File.Exists(Path.Combine(workspace.RootPath, "generated", "registrations", "PageFeatureRegistrationExtensions.g.cs")).ShouldBeTrue();
    }
}
