// <auto-generated />
// Generated by Incursa.Generators.Tool
// Command: incursa-appdefs
// Do not edit this file by hand. Your changes will be overwritten.
// Ownership: target=registrations; kind=page-registration-helper; relative-path=PageFeatureRegistrationExtensions.g.cs

#nullable enable

using System;
using Microsoft.Extensions.DependencyInjection;
using Example.Server.UiEngines;

namespace Example.Server.Generated;

public static class PageFeatureRegistrationExtensions
{
    public static IServiceCollection AddCustomerListUiEngine<TImplementation>(this IServiceCollection services)
        where TImplementation : class, ICustomerListUiEngine
    {
        ArgumentNullException.ThrowIfNull(services);
        services.AddScoped<ICustomerListUiEngine, TImplementation>();
        return services;
    }

}
